#!/usr/bin/env perl
use strict;
use warnings;

use Lingua::EN::Opinion;
use Statistics::Lite qw( mean );
use List::Util qw( min max sum0 );

my $input_file = shift || die "Usage: perl $0 /some/file.txt\n";

my $opinion = Lingua::EN::Opinion->new( file => $input_file );
$opinion->analyze();

my %score;
@score{ @{ $opinion->sentences } } = @{ $opinion->scores };

my $min = min( @{ $opinion->scores } );
my $max = max( @{ $opinion->scores } );

print "Most positive sentences:\n";
    for my $positive ( map { [ $score{$_} => $_ ] } @{ $opinion->sentences } ) {
        next unless $positive->[0] == $max;
        print "$positive->[1]\n";
    }
print "\n";
print "Most negative sentences:\n";
    for my $negative ( map { [ $score{$_} => $_ ] } @{ $opinion->sentences } ) {
        next unless $negative->[0] == $min;
        print "$negative->[1]\n";
    }
print "\n";
print 'Average sentence score: ', mean( @{ $opinion->scores } ), "\n";
print "\n";
print 'Total sentence score: ', sum0( @{ $opinion->scores } ), "\n";
